version: BUILD {build}
image: Visual Studio 2019
skip_branch_with_pr: true
environment:
  NUGET_API_KEY:
    secure: oy2a67zazeb3hhpq4nkawxxmggumsf7ejinyupfbijhluu
install:
  - ps: |
      $DOTNET_INSTALL_DIR = $(Join-Path (Get-Location) 'dotnetsdk')
      $dotnetReleasesUrl = 'https://dotnetcli.blob.core.windows.net/dotnet/release-metadata/releases-index.json'
      $dotnetReleases = $(Invoke-WebRequest $dotnetReleasesUrl | ConvertFrom-Json)."releases-index"
      function Install-LatestDotNetSdk($Channel) {
          $version = ($dotnetReleases | Where-Object { $_.'channel-version' -eq $channel }).'latest-sdk'
          powershell -NoProfile -ExecutionPolicy Unrestricted -Command "&([scriptblock]::Create((Invoke-WebRequest -UseBasicParsing 'https://dot.net/v1/dotnet-install.ps1'))) -Version $version -InstallDir $DOTNET_INSTALL_DIR -NoPath"
      }
      Install-LatestDotNetSdk -Channel '3.1'
      $env:Path = "$DOTNET_INSTALL_DIR;$env:Path"
before_build:
  - ps: |
      $mostRecentTag = git describe --abbrev=0 --tags --always
      if ($mostRecentTag.Substring(0, 1) -ne 'v') {
          $mostRecentTag = 'v1.0.0'
          if ($env:APPVEYOR_REPO_TAG -eq 'true') { exit 1 }
      }
      $mostRecentVersion = $mostRecentTag.Substring(1)
      $currentCommitHash = git rev-parse --short HEAD
      Set-AppveyorBuildVariable -Name SW_VER -Value $mostRecentVersion
      Update-AppveyorBuild -Version "Build $env:APPVEYOR_BUILD_NUMBER - Commit $currentCommitHash - Tag v$mostRecentVersion"
build_script:
  - ps: |
        nuget sources add -Name "nuget" -Source "https://api.nuget.org/v3/index.json" -username "Lucian_Aparaschivei" -password "$env:NUGET_API_KEY"
        dotnet pack --configuration Release
        dotnet nuget push "bin/Release/NLog.Extensions.AzureFileSystem.1.0.0.nupkg" --source "nuget" 
        if ($LastExitCode -ne 0) { exit $LastExitCode }