version: BUILD {build}
image: Visual Studio 2019
skip_branch_with_pr: true
environment:
  BUILDVERSION: ""
install:
  - ps: |
      $DOTNET_INSTALL_DIR = $(Join-Path (Get-Location) 'dotnetsdk')
      $dotnetReleasesUrl = 'https://dotnetcli.blob.core.windows.net/dotnet/release-metadata/releases-index.json'
      $dotnetReleases = $(Invoke-WebRequest $dotnetReleasesUrl | ConvertFrom-Json)."releases-index"
      function Install-LatestDotNetSdk($Channel) {
          $version = ($dotnetReleases | Where-Object { $_.'channel-version' -eq $channel }).'latest-sdk'
          powershell -NoProfile -ExecutionPolicy Unrestricted -Command "&([scriptblock]::Create((Invoke-WebRequest -UseBasicParsing 'https://dot.net/v1/dotnet-install.ps1'))) -Version $version -InstallDir $DOTNET_INSTALL_DIR -NoPath"
      }
      Install-LatestDotNetSdk -Channel '3.1'
      $env:Path = "$DOTNET_INSTALL_DIR;$env:Path"
before_build:
  - ps: |
      $mostRecentTag = git describe --abbrev=0 --tags --always
      if ($mostRecentTag.Substring(0, 1) -ne 'v') {
          $mostRecentTag = 'v1.0.0'
          if ($env:APPVEYOR_REPO_TAG -eq 'true') { exit 1 }
      }
      $mostRecentVersion = $mostRecentTag.Substring(1)
      $currentCommitHash = git rev-parse --short HEAD
      Set-AppveyorBuildVariable -Name SW_VER -Value $mostRecentVersion
      Update-AppveyorBuild -Version "Build $env:APPVEYOR_BUILD_NUMBER VE- Commit $currentCommitHash - Tag v$mostRecentVersion"
build_script:
  - ps: |
        $env:BUILDVERSION = "1.0.$env:APPVEYOR_BUILD_NUMBER"
        dotnet build NLog.Extensions.AzureFileSystem.sln -c Release --version-suffix=$env:APPVEYOR_BUILD_NUMBER /p:Version=$env:BUILDVERSION
        dotnet pack --configuration Release --version-suffix=$env:APPVEYOR_BUILD_NUMBER --include-symbols -o .\artifacts --no-build /p:Version=$env:BUILDVERSION

        if ($LastExitCode -ne 0) { exit $LastExitCode }

nuget:
  disable_publish_on_pr: true

artifacts:
  - name: NuGet Packages
    path: .\artifacts\**\*.nupkg
  - name: NuGet Symbol Packages
    path: .\artifacts\**\*.snupkg

deploy:
- provider: NuGet
  api_key:
    secure: kaV9++MNbasLJLDvD5ZzAQhZZ25W75diTaf/T3pKdPuLQFQ0QDqk3xXErARMuGG8
  skip_symbols: true
  on:
    branch: master
